// import { Buttonex } from "@/stories/Buttonex";
import { Button } from "@/components/Button";
import { Fragment } from "@/components/Fragment/Fragment";
import { H1, H4 } from "@/components/Heading";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        <Fragment>
          <div className={styles.hero}>
            <div className={styles.hero__left}>
              <H1>Whereas recognition of the inherent dignity</H1>
              <H4>
                Salon przesłon okiennych, systemów rolet i bram dla Twojego domu
                i firmy
              </H4>

              <Button
                label="Odwiedź nas"
                icon="eye"
                href="#"
                className={styles.hero__button}
              />
            </div>
            <div className={styles.hero__right}>
              <h1 className="title">Welcome to Next.js!</h1>
            </div>
          </div>
        </Fragment>
      </main>
    </>
  );
}
